#27 UserData class
ewa-krawczyk/user-data-test pull request #31
Opened 2021-04-14 16:52 UTC by ewa-krawczyk

2021-04-18 14:52 UTC, mwilczek-net requested changes
Please add getters and setters to other fields, as was shown on example

2021-04-18 14:52 UTC, mwilczek-net commented on index.js
> +};
Nearly 😄
Class has required fields, but JS do not restrict us with adding additional fields later -> one typo and half of program do not work as expected.
For example if somebody created user, and want to change it's name this will work: `user.firstnaaame='edward'`, but other parts of program do not know about `fisrtnaaame`, rather, it expects `firstName`.

To avoid it, we can use getter-setter convetion. For example:
```
class userData {
  constructor (fisrtName, lastName, phone, address) {
    this.fisrtName = fisrtName;
    this.lastName = lastName;
    this.phone = phone;
    this.address = address;
  }
  getFirstName() {
    return this.firstName();
  }
  setFirstName(firstName) {
    this.firstName = firstName;
  }
};
```

Now when somebody would try to set name and write wrong method name `user.setfirstnaaaame('edward')`, JS will break with error message - you will see that something is wrong 😀 .

2021-04-19 18:28 UTC, ewa-krawczyk commented
done

2021-04-19 18:28 UTC, ewa-krawczyk commented on index.js
> +};
done

2021-04-21 19:32 UTC, mwilczek-net approved these changes

2021-04-21 19:32 UTC, merged