#32 Lets add real user to list
ewa-krawczyk/user-data-test pull request #34
Opened 2021-05-08 12:05 UTC by ewa-krawczyk

2021-05-09 18:40 UTC, mwilczek-net requested changes

2021-05-09 18:40 UTC, mwilczek-net commented on index.js
> +  console.log( `selected: ${firstName}`);
Instead of printing value every time, as for everything, then print one report in a way:
```
Created user:
First Name: ${newUser.getFirstName()}
Last Name: ${newUser.getLastName()}
Phone Number: ${newUser.getNumber()}
Address: ${newUser.getAddress()}
```

2021-05-13 15:32 UTC, ewa-krawczyk commented on index.js
> +  console.log( `selected: ${firstName}`);
added

2021-05-13 15:33 UTC, ewa-krawczyk commented on index.js
> +  console.log( `selected: ${firstName}`);
added

2021-05-17 19:58 UTC, mwilczek-net approved these changes

2021-06-13 14:51 UTC, merged