#28 Remove should remove
ewa-krawczyk/user-data-test pull request #35
Opened 2021-05-08 12:05 UTC by ewa-krawczyk

2021-05-09 18:37 UTC, mwilczek-net requested changes

2021-05-09 18:37 UTC, mwilczek-net commented on index.js
> +  const selectedId = readlineSync.question(`Podaj liczbę od 0 do ${arrayLength -1 }: `);
Please use everywhere either English or Polish language

2021-05-13 15:02 UTC, ewa-krawczyk commented on index.js
> +  const selectedId = readlineSync.question(`Podaj liczbę od 0 do ${arrayLength -1 }: `);
done

2021-05-17 19:59 UTC, mwilczek-net approved these changes

2021-06-13 14:51 UTC, merged